apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: mysql-operator
build:
  artifacts:
    - image: mysql-operator # this needs to be same as image specified in config/manager/kustomization.yaml
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - config/crd
      - config/default
      - config/mysql # mysql cluster for testing. todo: will be moved to e2e.
# https://skaffold.dev/docs/testers/custom/ <- no doc about image
# test:
#   - image: gcr.io/k8s-skaffold/skaffold-example
#     custom:
#       - command: echo Hello world!!
