# permissions for end users to edit mysqlusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mysqluser-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mysql-operator
    app.kubernetes.io/part-of: mysql-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysqluser-editor-role
rules:
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqlusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqlusers/status
  verbs:
  - get
