# permissions for end users to edit mysqlusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqluser-editor-role
rules:
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqlusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.nakamasato.com
  resources:
  - mysqlusers/status
  verbs:
  - get
