apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: mysql-operator
build:
  artifacts:
    - image: mysql-operator # this needs to be same as image specified in config/manager/kustomization.yaml
      context: ..
      docker:
        dockerfile: Dockerfile
  local:
    push: false
deploy:
  kustomize:
    paths:
      - ../config/crd
      - ../config/default
