apiVersion: mysql.nakamasato.com/v1alpha1
kind: MySQLDB
metadata:
  labels:
    app.kubernetes.io/name: mysqldb
    app.kubernetes.io/instance: mysqldb-sample
    app.kubernetes.io/part-of: mysql-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mysql-operator
  name: mysqldb-sample
spec:
  # TODO(user): Add fields here
