apiVersion: mysql.nakamasato.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-sample
spec:
  host: localhost
  adminUser:
    name: root
    type: raw
  adminPassword:
    name: password
    type: raw
