apiVersion: mysql.nakamasato.com/v1alpha1
kind: MySQL
metadata:
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-sample
    app.kubernetes.io/part-of: mysql-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mysql-operator
  name: mysql-sample
spec:
  host: localhost
  adminUser:
    name: root
    type: raw
  adminPassword:
    name: password
    type: raw
