apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-nodeport
spec:
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    nodePort: 30306
  selector:
    app: mysql
  type: NodePort
