apiVersion: mysql.nakamasato.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-sample
spec:
  host: mysql.default # need to include namespace if you use Kubernetes Service as an endpoint.
  # gcp_secret_name: mysql-password # echo -n "password" | gcloud secrets create mysql-password --data-file=-
  admin_user: root
  admin_password: password
