apiVersion: mysql.nakamasato.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-sample
spec:
  host: mysql.default.svc.cluster.local # TODO: dial tcp: lookup mysql on 10.96.0.10:53: no such host
  admin_user: root
  admin_password: password
